Earthfile, dracut/02-kairos-setup-initramfs.conf, dracut/10-immucore.conf, dracut/28immucore/kairos-setup-initramfs.service, dracut/28immucore/module-setup.sh, dracut/50-kairos-initrd.conf, earthly.sh
If we are dropping cos-immutable-rootfs then we have to include the missing files that the package already added.
For example, the several dracut configs of modules for the initramfs stage, or the general config for the dracut file.
We also need to install and link the initramfs elemental stage service as that its no longer provided by the cos-immutable-rootfs package and not integrated into immucore yet
Signed-off-by: Itxaka <itxaka.garcia@spectrocloud.com>
=> Add extra files needed for dracut

internal/utils/mounts.go, pkg/mount/dag_steps.go, pkg/mount/state.go
Respect all options from systemd-fsck as that it what is currently used on kairos.
Fixes #55
=> Add fsck before mounting

internal/utils/common.go, internal/utils/mounts.go, main.go
After the UKI merge it was broken due mounting too many things at the start. That may work and be needed on UKI, but not on normal boots
Signed-off-by: Itxaka <itxaka.garcia@spectrocloud.com>
=> Fix master to boot normal

internal/utils/mounts.go, main.go, pkg/mount/dag_steps.go, pkg/mount/fs.go, pkg/mount/state.go
Adds support for:
- rd.cos.oemtimeout=
- rd.cos.overlay=tmpfs:SIZE
- rd.cos.overlay=LABEL=DEVICE_LABEL
- rd.cos.overlay=UUID=DEVICE_UUID
Fixes https://github.com/kairos-io/kairos/issues/991
=> Add missing cmdline stanzas

earthly.sh, internal/utils/mounts.go, pkg/mount/dag_steps.go, pkg/mount/state_test.go
Load the base overlay config from the cos-layout.env file. This means we have to depend the base overlay mount to the load-config step, which moves things a bit in the DAG.
Fixes: https://github.com/kairos-io/kairos/issues/999
=> :bug: Load overlay config from cos-layout.env

internal/utils/mounts.go, pkg/mount/dag_steps.go
Otherwise we are ignoring any override via stanza
Fixes: https://github.com/kairos-io/kairos/issues/1012
=> :bug: Get oem label from cmdline before using runtime

internal/utils/chroot.go, pkg/mount/state.go
We were mounting the whole /dev /sys and /run as MS_REC which means that it was also mounting any submounts that those original source had mounted.
This resulted in things like the /dev/sr0 or /sys/fs/cgroups/blkid subdirs being mounted and shared with the initramfs. Which means that trying to unmount them also tried to unmount them from initramfs and thatis a big no-no
This patch makes it so the specifics dirs that we need are mounted as MS_REC and the rest are normally mounted. It means we have to be more specific with our mounts for chroot and that we need to do checks before mounting (i.e. /run/rootfsbase doesnt exist in a normal mount) before mounting everything but this sets and clean the chroot correctly.
=> :bug: Fix chroot unmounting

dracut/28immucore/module-setup.sh
So we can run kcrypt as part of the stages inside the initramfs
=> :seedling: Add kcrypt binary to initramfs

internal/utils/mounts.go, pkg/mount/dag_live_media.go, pkg/mount/dag_normal_boot.go, pkg/mount/dag_steps.go, pkg/mount/dag_uki_boot.go, pkg/mount/state_test.go
This allows recovery squashfs to have oem mounted on boot so the stages runs correctly with user provided configs.
=> Try to mount oem under livemedia

dracut/28immucore/module-setup.sh, internal/constants/constants.go, internal/utils/mounts.go, pkg/mount/dag_normal_boot.go, pkg/mount/dag_steps.go, pkg/mount/state.go, pkg/mount/state_test.go
In case we want to support LVM to deliver the oem or persistent partitions, we need to activate lvm on immucore start so the devices appear under the /dev/disk/by-label properly
Fixes https://github.com/kairos-io/kairos/issues/997
=> :seedling: activate LVM volumes at the start

go.mod, go.sum, internal/utils/common.go, pkg/mount/state_test.go
On some devices, the disk can be a bit late to appear, so when getting
the state label and fs type it can lead to a direct failure.
This patch introduces a retry with a 1 second delay between tries in
order to obtain the state label. If that fails after all the retries it
also panics so we stop running immucore as it makes no sense.
Signed-off-by: Itxaka <itxaka.garcia@spectrocloud.com>
=> :bug: Retry getting the state label

internal/utils/mounts.go, pkg/mount/dag_steps.go, pkg/mount/operation.go, pkg/mount/state.go
sysroot mount was not being added to fstab due a combination of systemd mounting it (so it errored out as already mounted) and fstab ignoring that already mounted partition
Now we have a method of adding and avoiding duplicated entries and a check for that exact error
=> Fix missing sysroot mount in fstab

pkg/mount/dag_steps.go, pkg/mount/operation.go
As they are not critical, we can advise over them to pinpoint to a wrong config, but they are not critical and we dont expect them to work to have a working system
Fixes: https://github.com/kairos-io/kairos/issues/1367
=> Move some err to warnings

dracut/28immucore/module-setup.sh
Part of: https://github.com/kairos-io/kairos/issues/1831
`sfdisk` is a dependency of `growpart`.
=> Add sfdisk to initramfs

internal/utils/log.go, internal/utils/mounts.go, main.go, pkg/mount/dag_steps.go
Otherwise under uki, it cannot write the log to /run as it doesnt exist yet and then on boot we lose the full log of immucore which is bad for troubleshooting
=> Set basic /run mount from the start to be able to always log

pkg/mount/dag_steps.go
Usually systemd initrd takes care of adding the measurements to the PCR registers, but as we take over the initrd, nothing was being added, thus the final measurements didnt match.
This mimics systemd calling the measurements at the start of initrd and at the end of it, so later stages can extend the PCRs correctly
=> measure PCR phase

internal/constants/constants.go, pkg/mount/dag_steps.go, pkg/mount/dag_uki_boot.go
So the actual contents of the cdrom are available under that route, same as non-uki dracdut does.
=> Mount cdrom efiboot contents under /run/rootfsbase

pkg/mount/dag_steps.go
We were both matching rd.immucore.disable and
rd.immucore.disablesecureboot when trying to check if we want to disable immucore on livecd, which resulted in the wrong path being taken when trying to disable the secureboot check
=> Change the secureboot disable to not collide with disable immucore

internal/utils/mounts.go, pkg/mount/dag_steps.go, pkg/mount/state.go
main changes:
- make the mounts shared 
- mount more stuff (/dev/pts, /sys/kernel/security, /dev/shm, etc...)
- create dirs with proper permissions
- creates some special nodes for devices (migth be possible to remove)
- move existing mounts from / to /sysroot
- cp -r the dirs in rootfs that are not mounts into /sysroot as we are deleting the old sysroot afterwards
- only create target dirs if they are not there
- move /sysroot to be the new mount (hint, do it after chdir)
- do not chroot to run initramfs stage if we are on uki.
=> Fix mounts

internal/constants/constants.go, pkg/mount/dag_steps.go, pkg/mount/dag_uki_boot.go
When we did the changes to fix the mounts, the root dir was not remounted as RO.
This brings it back at the end of the dag and drops the not needed step in the middle as we are now pivoting into the fake sysroot
=> Recover the remount / RO

internal/utils/chroot.go, internal/utils/mounts.go, pkg/op/operation.go, pkg/state/steps_uki.go
This tries to bring more consistency when calling the mounts call and wraps them between `sync` calls - this is just an attempt trying to fix the bug that was reported about missing `sshd` user during boot (not allowing to login remotely on the box). 
The idea behind this is that there is a race condition going on, from the cloud config that quickly tries to add a bunch of users in sequence, and the overlay mount possibly not-ready-yet, or changes just not flushed to the disk yet
=> fix(mount): call sync before/after operations

pkg/dag/dag_uki_boot.go
Otherwise any files under oem that add stages to rootfs wont ever be run
=> Run rootfs stage after oem under uki

pkg/state/steps_uki.go
Instead of continuing booting which results in a broken system, we will log, wait 10 seconds and them reboot the instance
=> Exit properly if we cannot unlock partitions

internal/utils/mounts.go
Usually systemd would create those automatically but immucore mounts first the /run dir and if something needs to use those /run/lock dirs it will fail unless they create them.
So this patch creates some default dirs that we observed tmpfilesd to create on boot before systemd kicks in and creates them.
=> Add some missing run dirs on uki

internal/constants/constants.go
This makes disks available on boards that have MMC as booting/disk devices
=> Add modules for mmc disks

dracut/28immucore/module-setup.sh
Dracut inst_multiple does not fail if it cant find any of the required binaries, thus letting an initrafs in a broken state.
This patch adds a function that will first check for those binaries and fail if it cant find them, then if it can find all of them calls the inst_multiple to install them
Fixes https://github.com/kairos-io/kairos/issues/2692
Manually tested by changing the dockerfile to remove a needed package and running dracut:
```
RUN apt-get remove -y dosfstools
COPY module-setup.sh /usr/lib/dracut/modules.d/28immucore/module-setup.sh
RUN kernel=$(ls /lib/modules | head -n1) && dracut -f "/boot/initrd-${kernel}" "${kernel}"
```
```
+base-image *failed* | dracut[I]: Module 'memstrack' will not be installed, because command 'memstrack' could not be found!
+base-image *failed* | …
```
=> Fail if dracut cant install required binaries

internal/constants/constants.go, pkg/dag/dag_uki_boot.go, pkg/state/steps_uki.go
This help the transition between 3.3.x to 3.4.x by moving existing sysexts to their new places and creating the expected links so it should behave exactly like it was before
=> Add a UKI transition step

pkg/state/steps_shared.go
This enables adding the common sysext to the entries to enable
Part of https://github.com/kairos-io/kairos/issues/3331
Complements https://github.com/kairos-io/kairos-agent/pull/757
=> Enable the use of common sysexts

.goreleaser.yaml
Instead of assuming it was built correctly, check it and block its release if not
=> On tag check fips build
